### ISSUE TITLE
Warning: Failed Context Types error

### ISSUE THREAD

**Issue by aoshi321** [ratson/react-intl-redux#1]
Hi

Im integrating your module and everything works as expected except I get the following warning in the console:

Warning: Failed Context Types: Required context `intl.now` was not specified in `FormattedMessage`.

The formattedMessage component is using the same version of 'react-intl' that you are using as part of the module and the provider component is wrapped around around React-router component. Not sure if that is causing an issue.
```
import { Provider} from 'react-intl-redux';

<Provider store={store}>
    <Router routes={routes} history={browserHistory}/>
  </Provider>,
```
thanks

**Comment by ratson** [comment]
I have created an example with `react-router`, but I don't encounter the problem.
You may review the change to add `react-intl-redux` in https://github.com/ratson/react-intl-redux-example/commit/5f42a33580fa808b23f5acac16d5f777eb2781bf

Do you see any differences from the example to your setup? It would be great if you could create a full example to demonstrate the problem.

**Comment by ratson** [comment]
@aoshi321 Are you still getting the warning?

**Comment by ratson** [comment]
Closing this as do not have enough to proceed.
