### ISSUE TITLE
reference messages via props

### ISSUE THREAD

**Issue by adriaanbalt** [ratson/react-intl-redux#11]
I've built an app using React-Intl and now I'm trying to use your redux variant.  When I referenced messages not inside DOM elements but simply as JS injections I would write a line of code similar to this:

`this.props.intl.formatMessage({ id: 'greeting', defaultMessage: "not translated"  })`

This came in handle for this such as the placeholder of an input textfield.

However, I am unable to do the same in this case because I do not have `intl` on the `this.props`.

Can you suggest how I may do something similar in this case?

**Comment by ratson** [comment]
See https://github.com/yahoo/react-intl/wiki/API#injection-api

**Comment by adriaanbalt** [comment]
this also worked:
```js
import React, {Component, PropTypes} from 'react'
import {connect} from 'react-redux'
import {bindActionCreators} from 'redux'
import classNames from 'classnames'
import { injectIntl, FormattedMessage } from 'react-intl'; // Important

class LanguagePage extends Component
{
  render()
  {
    console.log ( "formatted msg: ", this.props.intl.formatMessage({ id: 'greeting', defaultMessage: "default"  }) )
    return (
      <div className="page language">
        <FormattedMessage id={`greeting`} defaultMessage={"default"} />
      </div>
    )
  }
}
const mapStateToProps = ({}) => { return {} }
const mapDispatchToProps = dispatch => bindActionCreators({}, dispatch)

// important: wrapping connect() with "injectIntl()"
export default injectIntl(connect(mapStateToProps, mapDispatchToProps)(LanguagePage)) 
```

**Comment by timoweiss** [comment]
as addition to @adriaanbalt solution:
If you have mapped the `intlReducer` as `intl`,  you need to rename your mapping or you pass a second parameter to `injectIntl()` as follows:
```javascript
export default injectIntl(connect(mapStateToProps, mapDispatchToProps)(LanguagePage, { intlPropName: 'altIntlName' }))
```
