### ISSUE TITLE
Dispatch undefined

### ISSUE THREAD

**Issue by Andersos** [ratson/react-intl-redux#12]
In the [docs](https://github.com/ratson/react-intl-redux#switch-locale-and-messages-on-request) this is the code used to update the store:

```js
dispatch(updateIntl({
  locale,
  messages,
}))
```

When doing this I'm getting the error:
`Uncaught ReferenceError: dispatch is not defined`

**Comment by ratson** [comment]
It means to be `store.dispatch`, fixed via https://github.com/ratson/react-intl-redux/commit/fe5f9c3174ac5b21a24d5464d09d1b0b2beec00a
