### ISSUE TITLE
Props are not passed to IntlProvider

### ISSUE THREAD

**Issue by MentalAtom** [ratson/react-intl-redux#13]
When using Provider as per the docs for React-intl itself:
https://github.com/yahoo/react-intl/wiki/Components#intl-provider-component 

The props for messaging are not being passed through. This causes issues as `messages` are always empty, despite being passed, and so errors are thrown.

**Comment by ratson** [comment]
I am not sure if I understand your question correctly.
Are you asking why the following is not supported?
```jsx
import {Provider} from 'react-intl-redux'

const App = () => (
  <Provider messages={messages}>
    <FormattedNumber value={1000}/>
  </Provider>
)
```
If that is your question, you should provide the `messages` in `initialState` as document in https://github.com/ratson/react-intl-redux#provide-locale-and-messages-on-load

Let me know if I understand your incorrectly.

**Comment by MentalAtom** [comment]
That is correct, but I do not understand why it works this way, when the react-intl component itself works differently. This is an expansion of that component, so it makes no sense to use a different API for providing messages.

**Comment by ratson** [comment]
I was initially allowing the behaviour, but soon run into https://github.com/ratson/react-intl-redux/issues/4
I think this better pattern for `redux` usage by always pulling state from store.

If you have better idea not breaking the usage of `store.getState()`, I am open to fix it.

**Comment by ratson** [comment]
Closing this as nothing is actionable.
