### ISSUE TITLE
How to set a different locale?

### ISSUE THREAD

**Issue by andreabioli** [ratson/react-intl-redux#2]
I see that if I pass '1000' as a value for the FormattedNumber component, it's correctly formatted as '1,000' (so the integration works!). But when I try to set a locale, as in
<Provider store={store} locale='it'>
It doesn't seem to consider italian locale: it should output '1.000', but it remains always as '1,000' (dot instead of a comma).
Thanks.

**Comment by ratson** [comment]
Update README with example on how to update the locale.
Let me know if I have missed anything.

**Comment by andreabioli** [comment]
Really perfect, thank you! :-)
