### ISSUE TITLE
formats prop for IntlProvider

### ISSUE THREAD

**Issue by romanenko** [ratson/react-intl-redux#24]
Hello! Thanks for great and simple to use module.

There is a feature in **react-intl** (not enough documented as far as I know): `formats` prop for `<IntlProvider>`. It adds ability to add custom formatting for currencies in `<FormattedNumber />`: https://github.com/yahoo/react-intl/issues/539#issuecomment-233974105 

It would be great if we could add this feature to this module as well. Is there a need for it?

**Comment by jkomusin** [comment]
If you put a 'formats' key under your 'intl' state in your redux store, I think it should get pulled in by the IntlProvider's mapStateToProps here: https://github.com/ratson/react-intl-redux/blob/master/src/components/IntlProvider.js#L8 Have you given that a try?

There may be something else under there causing problems, or perhaps something specific to your use case. If you can't get it to work, a code example might help clarify what your goal is.

**Comment by mewdriller** [comment]
@jkomusin: That approach does work, but the included [`updateIntl`](https://github.com/ratson/react-intl-redux/blob/master/src/index.js#L10) action-creator strips everything but `locale` and `messages` from the payload provided. If you manually override the payload (as below), it does work as expected.

```
import { set } from 'lodash/fp';
import { updateIntl } from 'react-intl-redux';
 
export const enhancedUpdateIntl = payload =>
  set('payload', payload, updateIntl(payload));
```
