### ISSUE TITLE
Testing strategy documentation

### ISSUE THREAD

**Issue by ashleyconnor** [ratson/react-intl-redux#28]
The `react-intl` project has a [test helper for enzyme](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#enzyme) in order to test components and assertions on values of `<FormattedMessage />`.

Since your library adds `redux` into the mix, the test helper `mountWithIntl` function doesn't work - failing with:

```
Invariant Violation: Could not find "store" in either the context or props of "Connect(Control)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Control)".
```

Could this be modified to work with `react-intl-redux`?

**Comment by ratson** [comment]
Looks like this should be a different package, it should belong to `devDependencies`.
Is there anything need to be added for creating such helper?

**Comment by ratson** [comment]
Close due to nothing actionable.
