### ISSUE TITLE
Performance issue with immutablejs

### ISSUE THREAD

**Issue by bhouser** [ratson/react-intl-redux#29]
I'm adding react-intl-redux with immutableJS to my project.  There's an example of how to do that here, which is awesome: https://github.com/ratson/react-intl-redux/blob/master/test/immutable.spec.js

I am however concerned about how (in the example) intlSelector calls .toJS() on the entire i18n state every time something/anything in the redux store changes.  This seems horrible for performance, especially if I have a large app with both frequent redux events and lots of i18n'd texts.

Am I misinterpreting this?  Any suggestions?

**Comment by bhouser** [comment]
Solution suggestion:

_What:_ To avoid evaluating with `.toJS()` on store changes where the i18n state hasn't changed, the prop returned in mapStateToProps should be an immutableJS object.  `connect` will compare with the old version when the store dispatches, and then do nothing if there were no changes.  Only if the state changed will `.toJS()` be called.

_How:_ Maybe there's a better way to do this, but I'm thinking: in the [IntlProvider component](https://github.com/ratson/react-intl-redux/blob/master/src/components/IntlProvider.js), instead of just wrapping `react-intl`'s `IntlProvider` component with connect, there could be a wrapping component which checks if the `intl` prop is an immutablejs instance, and if it is calls `.toJS()` before passing it to `react-intl`'s `IntlProvider`.

The downside of this approach is that immutableJS is a dependency even for people not using immutableJS.  Maybe there's a more elegant solution?

**Comment by ratson** [comment]
I am not familiar `ImmutableJS` how much it would cost for the `toJS()` call, it is better you measure it before optimize it.
I think you could simply memorize the `.toJS()` result, then you don't need pay too much cost for the conversion. Is that make sense?

**Comment by bhouser** [comment]
I haven't profiled it, I'm just going on the recommendation in the [redux doc's ImmutableJS recipe](http://redux.js.org/docs/recipes/UsingImmutableJS.html), where `toJS()` is described as "extremely slow".  It also strongly advises not using it in `mapStateToProps` because `toJS()` produces a new instance each time it's called, preventing `connect` from detecting that nothing changed.

However, your suggestion is actually very good: if I write a memoizing selector, or use reselect for example, `toJS()` will only be called when the i18n data in the store changed.  I didn't think of that.  Thanks!

**Comment by ratson** [comment]
If you could send a PR to help improving the example would be great :)
