### ISSUE TITLE
When using updateIntl, it's reseting the container state

### ISSUE THREAD

**Issue by idangozlan** [ratson/react-intl-redux#30]
For ex. if there's an open dialog (open state is defined on the container state), and using `updateIntl` it's getting closed (as the initial state)

**Comment by ratson** [comment]
Do you have dialog open in your store?

**Comment by idangozlan** [comment]
state, not store

**Comment by ratson** [comment]
I don't think you could preserve state when you change context, which `react-intl` relying on.
If you have suggestions on how it could be done, I am willing to learn.

**Comment by ratson** [comment]
Close due to nothing actionable.
