### ISSUE TITLE
react-intl-redux is preventing a react-bootstrap component from re-rendering

### ISSUE THREAD

**Issue by blair-anson** [ratson/react-intl-redux#31]
Hi, 
I'm seeing a strange issue where a call to `this.props.dispatch(updateIntl({ }); ` prevents a react-bootstrap Dropdown component from re-rendering when the local state changes.
I created an issue for this on Stackoverflow. If you can please take a look that would be great

http://stackoverflow.com/questions/43212603/redux-dispatch-prevents-re-rendering-of-react-bootstrap-dropdownbutton-when-loca

**Comment by ratson** [comment]
@blair-anson Would you try ` this.setState({value: eventKey}, () => this.updateLang(eventKey));` to see if it helps?

**Comment by ratson** [comment]
Close as no reply.
