### ISSUE TITLE
passing preloadedState (server-side-rendering) not properly setting the locale data on the client side

### ISSUE THREAD

**Issue by HoneyryderChuck** [ratson/react-intl-redux#33]
I've experienced this issue with the following versions: 

* react-intl-redux 0.4.1
* react-intl 2.2.3
* redux 3.6.0
* react-router 4.1.1
* react 15.4.2

I'm setting server side rendering and loading the messages from the json file in the server. the store is composed of `defaultLocale`, `locale`, and `messages`. When I send the request for the first page, I see the translated data, no warning, it works properly. 

However, on the client-side, it re-renders the page to the default locale. I was passing the preloadedState as specified in the redux documentation, so I got confused. I was also seeing the following warning client-side: `[React Intl] Missing locale data for locale: "pt". Using default locale: "en" as fallback.`. 

After some trial and error, I found why I was getting that: the locale defaults from react-intl weren't being loaded. So I added them in the client-side bootstrapping: 

```js
const locale = preloadedState.intl.locale || 'en'
const localeData = require('react-intl/locale-data/' + locale)
addLocaleData(localeData)
```

I don't know if this the recommended way to do it, but it seems to me that the store should have taken care of that, specifically when a locale is set/updated (that counts for language change as well), the locale-data should be loaded to prevent that "flash of unnecessary warnings".

Unless I haven't used the proper API. Still, I find it weird that the warning only happens in the client-side (server-side was rendering warning-free).

**Comment by ratson** [comment]
Thanks to raise the problem, please see https://github.com/yahoo/react-intl/wiki#loading-locale-data why you have to do that.
I have update README to mention this pitfall.
