### ISSUE TITLE
Unmount and mount IntlProvider child component on locale change

### ISSUE THREAD

**Issue by mbury** [ratson/react-intl-redux#34]
Hi, Is this the correct behavior when dispatching updateIntl() action with new locale, child of IntlProvider component is unmounted and mounted again?

**Comment by surajbyanju** [comment]
Did you figure this out? I am also having same issue. Every time I update the locale in updateIntl() action, the child components are unmounted and mounted again.

**Comment by ratson** [comment]
As `react-intl`'s `IntlProvidrer` receives the new props, which updates the `context`, I think it is normal for the child component to be re-rendered.

@mbury @surajbyanju Feel free to re-open if you know there is a way to avoid that.
