### ISSUE TITLE
Calling updateIntl not refreshing messages and loses locale data

### ISSUE THREAD

**Issue by LKay** [ratson/react-intl-redux#39]
I'm dispatching action `updateIntl` action inside other Thunk action and it correctly updates the redux state but none of the components wrapped in `injectIntl` or context base components get new locale. Everything just displays placholders and getting bunch of `[React Intl] Missing locale data for locale: "xx". Using default locale: "yy" as fallback.` errors in the console. 

Inside components' injected props `intl` still contains old locale data (from before dispatching an action) even though they are render after the redux state is updated with new locale data.

Is there some bug with this or do I need to do something else than just dispatching an action so my components get updated locale data?

**Comment by ratson** [comment]
@LKay Would you provide an example app to demo the problem? I could not tell what's wrong from your description.

**Comment by ratson** [comment]
Close as no reply.
