### ISSUE TITLE
Can't get initialization of Provider to store passed in props.

### ISSUE THREAD

**Issue by silasb** [ratson/react-intl-redux#4]
I'm using 

```jsx
<Provider store={store} locale="it" messages={messages}>
</Provider>
```

After rendering and doing a store.getState():

```json
"intl":{"locale":"en","messages":{}}
```

Expected:

```json
"intl":{"locale":"it","messages": {....}}
```

**Comment by ratson** [comment]
Thank you for reporting the issue, I did not consider this.
To fix it properly, should avoid passing props, but ask user to set them to `initialState`.

I will spend some time this weekend to address this, stay tuned.
Pull requests are welcome.

**Comment by lochstar** [comment]
I noticed this as well. I ended up setting the messages to `initialState`.

**Comment by ratson** [comment]
Updated README and added an example about this use case.
