### ISSUE TITLE
Usecases for integrating with Redux

### ISSUE THREAD

**Issue by oyeanuj** [ratson/react-intl-redux#42]
Hi @ratson, this is more of a question for the docs than an issue, so feel free to close it if not relevant. I am trying to add internationalization to a `react-redux` app, and wondering what usecases would make it ideal for integrating with `redux` (rather than just `react` by default)?

So, I am curious, what kind of usecases are people using this binding for, where it helps to have `intl` state in the store?

Thank you!

**Comment by ratson** [comment]
@oyeanuj I could not explain better than the [Redux doc](http://redux.js.org/docs/faq/General.html#when-should-i-use-redux).

> If you're just learning React, you should probably focus on thinking in React first, then look at Redux once you better understand React and how Redux might fit into your application.

`s/Redux/React Intl Redux/` should apply the same.
