### ISSUE TITLE
Follow semver for breaking changes

### ISSUE THREAD

**Issue by thisandagain** [ratson/react-intl-redux#43]
In many of the [recent releases](https://github.com/ratson/react-intl-redux/blob/master/CHANGELOG.md) of this module, breaking changes have been introduced with a minor version change. As is [conventional for the JavaScript ecosystem](https://docs.npmjs.com/getting-started/semantic-versioning) (particularly for those who are installing `react-intl-redux` using `npm`) it would be helpful to introduce these changes along with a major version bump. Without doing so, it causes some headaches for folks who are using this module by introducing unexpected bugs, breaking builds, and hassle. 

I'm hoping you might consider using [Semantic Versioning](http://semver.org/) going forward to help alleviate this issue. Thank you for considering and thank you for sharing your work! ❤️

**Comment by ratson** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I am using using minor version for breaking changes pre 1.0, anyone using `^0.y.z` should be fine.
Why would you think that is not semver?
