### ISSUE TITLE
FormattedMessage in a connected component

### ISSUE THREAD

**Issue by yentsun** [ratson/react-intl-redux#44]
I probably am missing something but is `FormattedMessage` supposed to work from a connected component?

I took this example https://github.com/ratson/react-intl-redux/blob/master/examples/multiple-languages/src/index.js and modified it like so:

1. Moved `FormattedMessage` part into a separate component:

```
class Sample extends React.Component {
    render() {
        return(
            <p>
                <FormattedMessage id="app.greeting" defaultMessage="Hello!" />
            </p>
        );
    }
}
const SampleConnected = connect()(Sample);
```

2. Root app now looks like this:
```
<Provider store={store}>
                <IntlProvider>
                    <div>
                        <SampleConnected/>
                        <p>
                            <button onClick={this.handleLoadlLocales}>
                                Local locales
                            </button>{' '}
                            <SwitchLocale />
                        </p>
                        <DevTools />
                    </div>
                </IntlProvider>
            </Provider>
```

...and I couldn't get locale switching to work with this code (the action dispatches normally):

![selection_055](https://user-images.githubusercontent.com/630971/33272717-91100944-d3bd-11e7-87b7-9f8a21937e1a.png)

If I use a non-connected component:
```
<Provider store={store}>
                <IntlProvider>
                    <div>
                        <Sample/>
                        <p>
                            <button onClick={this.handleLoadlLocales}>
                                Local locales
                            </button>{' '}
                            <SwitchLocale />
                        </p>
                        <DevTools />
                    </div>
                </IntlProvider>
            </Provider>
```
locale switch works fine:

![selection_056](https://user-images.githubusercontent.com/630971/33272881-2c1c583e-d3be-11e7-9be8-c131bcf91d86.png)

**Comment by ratson** [comment]
@yentsun Updated README, please refer to https://github.com/ratson/react-intl-redux#troubleshooting

**Comment by yentsun** [comment]
@ratson oh, ok - thanks
