### ISSUE TITLE
multiple-languages demo doesn't work (greeting does not update when changing locale)

### ISSUE THREAD

**Issue by mrfelton** [ratson/react-intl-redux#53]
Hi, it seems that the multiple-languages demo doesn't function properly.

Clicking the "local locales" button causes the locale data to be loaded into the state and the dropdown to be populated.

Selecting a language from the dropdown causes the `state.intl` data to update correctly.

But the greeting on the page never updates to reflect the changes.

There is an error in the console that says

> index.js:2214 [React Intl] Missing locale data for locale: "it". Using default locale: "en" as fallback.

Whichever language you select, the locale data is reported as missing and it always just displays the default english text

**Comment by ratson** [comment]
@mrfelton Thanks for reporting. Did you try to change the example to use the release version? It may related to the recent changes, I will find time to test it more throughly, feel free to submit PR if you find anything.

**Comment by mrfelton** [comment]
No, I literally cloned the repo, installed it, and tried to run the example.

**Comment by ostrichegret** [comment]
@ratson hi ratson, on latest commit the example still got error when using npm install ( and npm prepare ) at:
del node_modules/react-intl-redux/node_modules

the script works fine after manually delete the folder "node_modules/react-intl-redux/node_modules"

Thanks for the great works
