### ISSUE TITLE
react-intl version 3

### ISSUE THREAD

**Issue by geovie** [ratson/react-intl-redux#59]
Hi, are there any plans to update `react-intl-redux` to `react-intl` version 3 and maybe typescript?

Would a PR be welcomed?

**Comment by ratson** [comment]
PR is welcome, it is better to have 2 separate PRs.

**Comment by eponae** [comment]
Hi

I was wondering if you were planning on merging the pull request soon and releasing a new version ? Thank you very much for your answer
