### ISSUE TITLE
Remove props.key workaround

### ISSUE THREAD

**Issue by ratson** [ratson/react-intl-redux#7]
Pull request https://github.com/ratson/react-intl-redux/pull/6 introduced a workaround for https://github.com/facebook/react/issues/2517.
Should be removed when React fixed it.

**Comment by gerhardsletten** [comment]
I am also experience trouble with this. If I connect a component to state.intl.locale the `componentWillReceiveProps` function is not called when locale is changed in store.

```js
componentWillReceiveProps (nextProps) {
  if (this.props.intLang !== nextProps.intLang) {
    console.log('page locale', this.props.intLang, ' => ', nextProps.intLang)
  }
}
```

But if I remove the `key` in `mapStateToProps` in `IntlProvider` it works as expected.

```
const mapStateToProps = (state, {intlSelector = defaultSelector}) => {
  const intl = intlSelector(state)
  return {
    ...intl
  }
}
```

**Comment by ratson** [comment]
@gerhardsletten From my test, I don't experience this problem, so I am planning to remove this hack and use the `intlSelector` directly, so anyone need this could provide their own `intlSelector`. What do you think?

**Comment by gerhardsletten** [comment]
Sorry, been some time since I touched this, but in this use-case we also kept an preference-reducer, so we connected our views to it to re-render / load localized content in the newly chosen language. It was a stack with many players, so it could be some other dependency which made the componentWillReceiveProps check not work.

**Comment by ratson** [comment]
A custom `intlSelector` with `key` property is equivalent to this hack, so people need this could provide their implementation.

**Comment by kimmoahola** [comment]
Hi @ratson, removing the key broke our app.

Is this a good workaround (or is there a simpler one?) to the problem where changing locale does not re-render components?

<pre>
import { connect } from 'react-redux';
import { IntlProvider } from 'react-intl';

function defaultSelector(state) {
  return {
    ...state.intl,
    key: state.intl.locale,
  };
}

const mapStateToProps = (state, { intlSelector = defaultSelector }) => intlSelector(state);

export default connect(mapStateToProps)(IntlProvider);
</pre>

And then use it like:

<pre>
import { Provider } from 'react-redux';
import CustomIntlProvider from './i18n/customIntlProvider';
import RoutedApp from './RoutedApp';

....

  render() {
    return (
      &lt;Provider store={store}&gt;
        &lt;CustomIntlProvider&gt;
          &lt;RoutedApp /&gt;
        &lt;/CustomIntlProvider&gt;
      &lt;/Provider&gt;
    );
  }
</pre>
