### ISSUE TITLE
Server Render?

### ISSUE THREAD

**Issue by WapGeaR** [ratson/react-intl-redux#9]
Pleaes, answer me, how to create server-render for this module?
In my initialState on server I receive empty reducer data, but on client I receive normal reducer data for react-intl-redux.
Can anyone give me example how to make it correct?

**Comment by ratson** [comment]
If you pass `initialState` to `createStore`, it should work on both client-side and server-side.

Would you create a minimal example about how you do SSR, so I could see what goes wrong?

**Comment by WapGeaR** [comment]
Server render function : 
`function handleRender(req, res) {
    const params = qs.parse(req.query)
    const store = configureStore(false)
    const memoryHistory = createMemoryHistory(req.url)
    const history = syncHistoryWithStore(memoryHistory, store)
    const html = renderToString(
        <Provider store={store}>
          {getRoutes(checkAuth, history)}
        </Provider>)
    const finalState = store.getState()
    res.send(renderFullPage(html, finalState))
}`

Client code: 
`
ReactDOM.render(
  <Provider store={store}>
    {getRoutes(checkAuth, history)}
  </Provider>,
  document.getElementById('app')
)
`

Provider import: 
`import {Provider} from 'react-intl-redux'`

And reducers code: 
`
import {intlReducer} from 'react-intl-redux'
import {addLocaleData} from 'react-intl'
import en from 'react-intl/locale-data/en'
import fr from 'react-intl/locale-data/fr'

addLocaleData(en)
addLocaleData(fr)


export default function configureStore(server) {
    const store = createStore(combineReducers({
        ...reducers,
        routing: routerReducer,
        intl: intlReducer,
    }), compose(
        responsiveStoreEnhancer,
        applyMiddleware(thunk)))

    if (module.hot) {
        // Enable Webpack hot module replacement for reducers
        module.hot.accept('./../redux/modules', () => {
            const nextRootReducer = require('./../redux/modules').default
            store.replaceReducer(nextRootReducer)
        })
    }

    return store
}
`

**Comment by ratson** [comment]
The second argument of [`createStore`](https://github.com/reactjs/redux/blob/master/docs/api/createStore.md#createstorereducer-preloadedstate-enhancer) is `preloadedState`, I think you should pass `undefined` to it.

**Comment by ratson** [comment]
@WapGeaR Would you let me know if the above solution works for you?

**Comment by ratson** [comment]
Close because of no reply, feel free to reopen.
